/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Usuarios */
        get: operations["listar_usuarios_api_v1_users__get"];
        put?: never;
        /** Crear Usuario */
        post: operations["crear_usuario_api_v1_users__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Contenidos Publicos */
        get: operations["listar_contenidos_publicos_api_v1_contenidos__get"];
        put?: never;
        /** Crear Contenido */
        post: operations["crear_contenido_api_v1_contenidos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Contenidos
         * @description Busca en el catálogo público por título, descripción y etiquetas (FTS5).
         *
         *     Declarado ANTES de ``/contenidos/{contenido_id}`` para que el segmento ``buscar``
         *     no se intente validar como UUID. ``q`` vacío o sin términos útiles devuelve [].
         */
        get: operations["buscar_contenidos_api_v1_contenidos_buscar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Contenido */
        get: operations["obtener_contenido_api_v1_contenidos__contenido_id__get"];
        /** Actualizar Contenido */
        put: operations["actualizar_contenido_api_v1_contenidos__contenido_id__put"];
        post?: never;
        /** Borrar Contenido */
        delete: operations["borrar_contenido_api_v1_contenidos__contenido_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subir Html Interactivo
         * @description Sube el fichero HTML de un ejercicio interactivo (NO se sanea, §10).
         */
        post: operations["subir_html_interactivo_api_v1_contenidos__contenido_id__html_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}/publicar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publicar Contenido */
        post: operations["publicar_contenido_api_v1_contenidos__contenido_id__publicar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restaurar Contenido */
        post: operations["restaurar_contenido_api_v1_contenidos__contenido_id__restaurar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}/versiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Versiones
         * @description Historial de versiones (snapshots) de un contenido, de la más antigua a la más reciente.
         */
        get: operations["listar_versiones_api_v1_contenidos__contenido_id__versiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}/versiones/{version_no}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaurar Version
         * @description Restaura el contenido al estado de una versión anterior (crea una versión nueva, §7).
         */
        post: operations["restaurar_version_api_v1_contenidos__contenido_id__versiones__version_no__restaurar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contenidos/{contenido_id}/purgar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Purgar Contenido
         * @description Elimina DEFINITIVAMENTE un contenido de la papelera (irreversible, solo admin).
         */
        delete: operations["purgar_contenido_api_v1_contenidos__contenido_id__purgar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/contenidos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Todos Admin */
        get: operations["listar_todos_admin_api_v1_admin_contenidos__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/ciclos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Ciclos */
        get: operations["listar_ciclos_api_v1_taxonomy_ciclos__get"];
        put?: never;
        /** Crear Ciclo */
        post: operations["crear_ciclo_api_v1_taxonomy_ciclos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/ciclos/{ciclo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Ciclo */
        get: operations["obtener_ciclo_api_v1_taxonomy_ciclos__ciclo_id__get"];
        /** Actualizar Ciclo */
        put: operations["actualizar_ciclo_api_v1_taxonomy_ciclos__ciclo_id__put"];
        post?: never;
        /** Eliminar Ciclo */
        delete: operations["eliminar_ciclo_api_v1_taxonomy_ciclos__ciclo_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/cursos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Cursos */
        get: operations["listar_cursos_api_v1_taxonomy_cursos__get"];
        put?: never;
        /** Crear Curso */
        post: operations["crear_curso_api_v1_taxonomy_cursos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/cursos/{curso_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Curso */
        get: operations["obtener_curso_api_v1_taxonomy_cursos__curso_id__get"];
        /** Actualizar Curso */
        put: operations["actualizar_curso_api_v1_taxonomy_cursos__curso_id__put"];
        post?: never;
        /** Eliminar Curso */
        delete: operations["eliminar_curso_api_v1_taxonomy_cursos__curso_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/asignaturas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Asignaturas */
        get: operations["listar_asignaturas_api_v1_taxonomy_asignaturas__get"];
        put?: never;
        /** Crear Asignatura */
        post: operations["crear_asignatura_api_v1_taxonomy_asignaturas__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taxonomy/asignaturas/{asignatura_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Asignatura */
        get: operations["obtener_asignatura_api_v1_taxonomy_asignaturas__asignatura_id__get"];
        /** Actualizar Asignatura */
        put: operations["actualizar_asignatura_api_v1_taxonomy_asignaturas__asignatura_id__put"];
        post?: never;
        /** Eliminar Asignatura */
        delete: operations["eliminar_asignatura_api_v1_taxonomy_asignaturas__asignatura_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener configuración del sitio */
        get: operations["obtener_configuracion_api_v1_config__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar ajustes generales (nombre del sitio y fuente) */
        put: operations["actualizar_ajustes_generales_api_v1_config_general_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/paleta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Activar paleta */
        put: operations["activar_paleta_api_v1_config_paleta_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/paletas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Añadir paleta personalizada */
        post: operations["agregar_paleta_api_v1_config_paletas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/paletas/{paleta_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Actualizar paleta personalizada */
        put: operations["actualizar_paleta_api_v1_config_paletas__paleta_id__put"];
        post?: never;
        /** Eliminar paleta personalizada */
        delete: operations["eliminar_paleta_api_v1_config_paletas__paleta_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/imagenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir Imagen */
        post: operations["subir_imagen_api_v1_media_imagenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/visitas/{contenido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Visita
         * @description Anota una visita anónima a un contenido (público).
         *
         *     Solo incrementa un contador en memoria; NO escribe en la BD (CLAUDE.md §8). La tarea de
         *     mantenimiento vuelca los conteos por lotes. Sin datos del visitante (§10).
         */
        post: operations["registrar_visita_api_v1_analytics_visitas__contenido_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/visitas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener Visitas
         * @description Total de visitas y desglose por contenido (solo admin). Refleja lo ya volcado a la BD.
         */
        get: operations["obtener_visitas_api_v1_analytics_visitas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Auditoria
         * @description Registro de acciones de gestión, más recientes primero (solo admin).
         */
        get: operations["listar_auditoria_api_v1_auditoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Backups
         * @description Lista las copias de seguridad existentes (de la más reciente a la más antigua).
         */
        get: operations["listar_backups_api_v1_admin_backups_get"];
        put?: never;
        /**
         * Crear Backup
         * @description Genera una copia de seguridad de la BD de inmediato y rota las antiguas.
         */
        post: operations["crear_backup_api_v1_admin_backups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/backups/{nombre}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar Backup
         * @description Descarga el fichero de una copia de seguridad (solo admin).
         *
         *     El nombre se valida en el servicio (formato exacto + contención en el directorio de
         *     copias) para impedir cualquier path traversal. Se sirve como adjunto para que el
         *     navegador lo descargue al PC del administrador.
         */
        get: operations["descargar_backup_api_v1_admin_backups__nombre__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exportar Todo
         * @description Genera y descarga la exportación completa (BD + media) como ``.tar.gz`` (solo admin).
         *
         *     Con este archivo se puede migrar el servidor o recuperar el sitio entero. Se construye
         *     en un temporal bajo el directorio de backups y se elimina después de enviarlo.
         */
        post: operations["exportar_todo_api_v1_admin_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar Todo
         * @description Restaura el sitio (BD + media) desde una exportación ``.tar.gz`` (solo admin).
         *
         *     Operación **destructiva**: reemplaza la base de datos y restaura la media. Exige escribir
         *     ``IMPORTAR`` en ``confirmacion`` y crea automáticamente una copia de seguridad de la BD
         *     actual antes de sobrescribir. Tras importar, la BD se migra al esquema actual. La sesión
         *     del administrador puede dejar de ser válida (el usuario procede de la BD importada).
         */
        post: operations["importar_todo_api_v1_admin_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivarPaletaRequest */
        ActivarPaletaRequest: {
            /** Paleta Id */
            paleta_id: string;
        };
        /** ActualizarAsignaturaRequest */
        ActualizarAsignaturaRequest: {
            /** Nombre */
            nombre?: string | null;
            /** Color */
            color?: string | null;
            /** Transversal */
            transversal?: boolean | null;
        };
        /** ActualizarCicloRequest */
        ActualizarCicloRequest: {
            /** Nombre */
            nombre?: string | null;
            /** Orden */
            orden?: number | null;
        };
        /** ActualizarContenidoRequest */
        ActualizarContenidoRequest: {
            /** Titulo */
            titulo?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /** Body Html */
            body_html?: string | null;
            /** Etiquetas */
            etiquetas?: string[] | null;
            /** Ciclo Id */
            ciclo_id?: string | null;
            /** Curso Id */
            curso_id?: string | null;
            /** Asignatura Id */
            asignatura_id?: string | null;
        };
        /** ActualizarCursoRequest */
        ActualizarCursoRequest: {
            /** Nombre */
            nombre?: string | null;
            /** Orden */
            orden?: number | null;
        };
        /** AjustesGeneralesRequest */
        AjustesGeneralesRequest: {
            /** Nombre Sitio */
            nombre_sitio: string;
            /** Fuente Activa */
            fuente_activa: string;
            /**
             * Fondo Activo
             * @default ninguno
             */
            fondo_activo: string;
            /**
             * Fondo Estilo
             * @default ordenado
             */
            fondo_estilo: string;
            /**
             * Logo Url
             * @default
             */
            logo_url: string;
            /**
             * Aula Abierta Label
             * @default Aula Abierta
             */
            aula_abierta_label: string;
            /**
             * Aula Abierta Emoji
             * @default 🌟
             */
            aula_abierta_emoji: string;
            /**
             * Catalogo Titulo
             * @default ¿En qué curso estás?
             */
            catalogo_titulo: string;
            /**
             * Catalogo Subtitulo
             * @default Toca tu curso para ver las actividades
             */
            catalogo_subtitulo: string;
            /** Donaciones */
            donaciones?: components["schemas"]["DonacionRequest"][];
            /** Redes Sociales */
            redes_sociales?: components["schemas"]["RedSocialRequest"][];
            /**
             * Publicidad Activa
             * @default false
             */
            publicidad_activa: boolean;
            /**
             * Publicidad Html Izquierda
             * @default
             */
            publicidad_html_izquierda: string;
            /**
             * Publicidad Html Derecha
             * @default
             */
            publicidad_html_derecha: string;
        };
        /** AsignaturaResponse */
        AsignaturaResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Color */
            color: string;
            /** Transversal */
            transversal: boolean;
        };
        /** AuditoriaEntradaResponse */
        AuditoriaEntradaResponse: {
            /** Id */
            id: string;
            /** Usuario Id */
            usuario_id: string | null;
            /** Usuario Email */
            usuario_email: string;
            /** Usuario Rol */
            usuario_rol: string;
            /** Accion */
            accion: string;
            /** Entidad */
            entidad: string;
            /** Entidad Id */
            entidad_id: string | null;
            /** Detalle */
            detalle: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AuditoriaListResponse */
        AuditoriaListResponse: {
            /** Total */
            total: number;
            /** Entradas */
            entradas: components["schemas"]["AuditoriaEntradaResponse"][];
        };
        /** BackupResponse */
        BackupResponse: {
            /** Nombre */
            nombre: string;
            /** Tamano Bytes */
            tamano_bytes: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** Body_importar_todo_api_v1_admin_import_post */
        Body_importar_todo_api_v1_admin_import_post: {
            /** Fichero */
            fichero: string;
            /** Confirmacion */
            confirmacion: string;
        };
        /** Body_login_api_v1_auth_token_post */
        Body_login_api_v1_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_subir_html_interactivo_api_v1_contenidos__contenido_id__html_post */
        Body_subir_html_interactivo_api_v1_contenidos__contenido_id__html_post: {
            /** Fichero */
            fichero: string;
        };
        /** Body_subir_imagen_api_v1_media_imagenes_post */
        Body_subir_imagen_api_v1_media_imagenes_post: {
            /** Fichero */
            fichero: string;
        };
        /** CicloResponse */
        CicloResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Orden */
            orden: number;
        };
        /** ConfiguracionResponse */
        ConfiguracionResponse: {
            /** Nombre Sitio */
            nombre_sitio: string;
            /** Paleta Activa */
            paleta_activa: string;
            /** Fuente Activa */
            fuente_activa: string;
            /** Fondo Activo */
            fondo_activo: string;
            /** Fondo Estilo */
            fondo_estilo: string;
            /** Logo Url */
            logo_url: string;
            /** Aula Abierta Label */
            aula_abierta_label: string;
            /** Aula Abierta Emoji */
            aula_abierta_emoji: string;
            /** Catalogo Titulo */
            catalogo_titulo: string;
            /** Catalogo Subtitulo */
            catalogo_subtitulo: string;
            /** Donaciones */
            donaciones: components["schemas"]["DonacionResponse"][];
            /** Redes Sociales */
            redes_sociales: components["schemas"]["RedSocialResponse"][];
            /** Publicidad Activa */
            publicidad_activa: boolean;
            /** Publicidad Html Izquierda */
            publicidad_html_izquierda: string;
            /** Publicidad Html Derecha */
            publicidad_html_derecha: string;
            /** Paletas Personalizadas */
            paletas_personalizadas: components["schemas"]["PaletaResponse"][];
        };
        /** ContenidoResponse */
        ContenidoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Titulo */
            titulo: string;
            /** Descripcion */
            descripcion: string;
            /** Tipo */
            tipo: string;
            /** Autor Id */
            autor_id: string | null;
            /** Publicado */
            publicado: boolean;
            /** Borrado */
            borrado: boolean;
            /** Idioma */
            idioma: string;
            /** Etiquetas */
            etiquetas: string[];
            /** Ciclo Id */
            ciclo_id: string | null;
            /** Curso Id */
            curso_id: string | null;
            /** Asignatura Id */
            asignatura_id: string | null;
            /** Hash Html */
            hash_html: string | null;
            /** Body Html */
            body_html: string | null;
            /** Sandbox Url */
            sandbox_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CrearAsignaturaRequest */
        CrearAsignaturaRequest: {
            /** Nombre */
            nombre: string;
            /**
             * Color
             * @default #6366f1
             */
            color: string;
            /**
             * Transversal
             * @default false
             */
            transversal: boolean;
        };
        /** CrearCicloRequest */
        CrearCicloRequest: {
            /** Nombre */
            nombre: string;
            /**
             * Orden
             * @default 0
             */
            orden: number;
        };
        /** CrearContenidoRequest */
        CrearContenidoRequest: {
            /** Titulo */
            titulo: string;
            /**
             * Descripcion
             * @default
             */
            descripcion: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "interactivo" | "texto";
            /**
             * Idioma
             * @default es
             */
            idioma: string;
            /**
             * Etiquetas
             * @default []
             */
            etiquetas: string[];
            /** Body Html */
            body_html?: string | null;
            /** Ciclo Id */
            ciclo_id?: string | null;
            /** Curso Id */
            curso_id?: string | null;
            /** Asignatura Id */
            asignatura_id?: string | null;
        };
        /** CrearCursoRequest */
        CrearCursoRequest: {
            /** Nombre */
            nombre: string;
            /**
             * Ciclo Id
             * Format: uuid
             */
            ciclo_id: string;
            /**
             * Orden
             * @default 0
             */
            orden: number;
        };
        /** CrearUsuarioRequest */
        CrearUsuarioRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Rol
             * @enum {string}
             */
            rol: "admin" | "editor";
        };
        /** CursoResponse */
        CursoResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /**
             * Ciclo Id
             * Format: uuid
             */
            ciclo_id: string;
            /** Orden */
            orden: number;
        };
        /** DonacionRequest */
        DonacionRequest: {
            /** Etiqueta */
            etiqueta: string;
            /** Url */
            url: string;
        };
        /** DonacionResponse */
        DonacionResponse: {
            /** Etiqueta */
            etiqueta: string;
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImagenSubidaResponse */
        ImagenSubidaResponse: {
            /** Url */
            url: string;
        };
        /** ImportResponse */
        ImportResponse: {
            /** Ok */
            ok: boolean;
            /** Num Ficheros Media */
            num_ficheros_media: number;
            /** App Version Importada */
            app_version_importada: string;
            /** Backup Seguridad */
            backup_seguridad: string | null;
            /** Detalle */
            detalle: string;
        };
        /** PaletaRequest */
        PaletaRequest: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Bg */
            bg: string;
            /** Surface */
            surface: string;
            /** Fg */
            fg: string;
            /** Primary */
            primary: string;
        };
        /** PaletaResponse */
        PaletaResponse: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Bg */
            bg: string;
            /** Surface */
            surface: string;
            /** Fg */
            fg: string;
            /** Primary */
            primary: string;
        };
        /** RedSocialRequest */
        RedSocialRequest: {
            /** Red */
            red: string;
            /** Url */
            url: string;
        };
        /** RedSocialResponse */
        RedSocialResponse: {
            /** Red */
            red: string;
            /** Url */
            url: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UsuarioResponse */
        UsuarioResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Rol */
            rol: string;
            /** Activo */
            activo: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Version No */
            version_no: number;
            /** Titulo */
            titulo: string;
            /** Tipo */
            tipo: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            /** Created By Email */
            created_by_email?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** VisitasResponse */
        VisitasResponse: {
            /** Total */
            total: number;
            /** Por Contenido */
            por_contenido: {
                [key: string]: number;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_usuarios_api_v1_users__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"][];
                };
            };
        };
    };
    crear_usuario_api_v1_users__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_contenidos_publicos_api_v1_contenidos__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"][];
                };
            };
        };
    };
    crear_contenido_api_v1_contenidos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearContenidoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_contenidos_api_v1_contenidos_buscar_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_contenido_api_v1_contenidos__contenido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_contenido_api_v1_contenidos__contenido_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarContenidoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    borrar_contenido_api_v1_contenidos__contenido_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subir_html_interactivo_api_v1_contenidos__contenido_id__html_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_subir_html_interactivo_api_v1_contenidos__contenido_id__html_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publicar_contenido_api_v1_contenidos__contenido_id__publicar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restaurar_contenido_api_v1_contenidos__contenido_id__restaurar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_versiones_api_v1_contenidos__contenido_id__versiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restaurar_version_api_v1_contenidos__contenido_id__versiones__version_no__restaurar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
                version_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purgar_contenido_api_v1_contenidos__contenido_id__purgar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_todos_admin_api_v1_admin_contenidos__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContenidoResponse"][];
                };
            };
        };
    };
    listar_ciclos_api_v1_taxonomy_ciclos__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CicloResponse"][];
                };
            };
        };
    };
    crear_ciclo_api_v1_taxonomy_ciclos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearCicloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_ciclo_api_v1_taxonomy_ciclos__ciclo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ciclo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CicloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_ciclo_api_v1_taxonomy_ciclos__ciclo_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ciclo_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarCicloRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CicloResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_ciclo_api_v1_taxonomy_ciclos__ciclo_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ciclo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_cursos_api_v1_taxonomy_cursos__get: {
        parameters: {
            query?: {
                ciclo_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_curso_api_v1_taxonomy_cursos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearCursoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_curso_api_v1_taxonomy_cursos__curso_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curso_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_curso_api_v1_taxonomy_cursos__curso_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curso_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarCursoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_curso_api_v1_taxonomy_cursos__curso_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                curso_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_asignaturas_api_v1_taxonomy_asignaturas__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsignaturaResponse"][];
                };
            };
        };
    };
    crear_asignatura_api_v1_taxonomy_asignaturas__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearAsignaturaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_asignatura_api_v1_taxonomy_asignaturas__asignatura_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asignatura_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsignaturaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_asignatura_api_v1_taxonomy_asignaturas__asignatura_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asignatura_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarAsignaturaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsignaturaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_asignatura_api_v1_taxonomy_asignaturas__asignatura_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asignatura_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_configuracion_api_v1_config__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionResponse"];
                };
            };
        };
    };
    actualizar_ajustes_generales_api_v1_config_general_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AjustesGeneralesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activar_paleta_api_v1_config_paleta_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivarPaletaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agregar_paleta_api_v1_config_paletas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaletaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_paleta_api_v1_config_paletas__paleta_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paleta_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaletaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_paleta_api_v1_config_paletas__paleta_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paleta_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subir_imagen_api_v1_media_imagenes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_subir_imagen_api_v1_media_imagenes_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImagenSubidaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_visita_api_v1_analytics_visitas__contenido_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contenido_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_visitas_api_v1_analytics_visitas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitasResponse"];
                };
            };
        };
    };
    listar_auditoria_api_v1_auditoria_get: {
        parameters: {
            query?: {
                limite?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriaListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_backups_api_v1_admin_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupResponse"][];
                };
            };
        };
    };
    crear_backup_api_v1_admin_backups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupResponse"];
                };
            };
        };
    };
    descargar_backup_api_v1_admin_backups__nombre__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nombre: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportar_todo_api_v1_admin_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    importar_todo_api_v1_admin_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_importar_todo_api_v1_admin_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
