"""Puerto AuthService: operaciones de contraseña y tokens. Implementado en infraestructura."""

from __future__ import annotations

from typing import Protocol


class AuthService(Protocol):
    def hash_password(self, plain: str) -> str: ...
    def verify_password(self, plain: str, hashed: str) -> bool: ...
    def create_access_token(self, subject: str, rol: str) -> str: ...
    def decode_token(self, token: str) -> dict[str, str]: ...
