"""Puertos (interfaces de repositorio) del contexto TAXONOMÍA."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.contexts.taxonomy.domain.model import Asignatura, Ciclo, Curso


class CicloRepository(Protocol):
    def add(self, ciclo: Ciclo) -> None: ...
    def get(self, ciclo_id: UUID) -> Ciclo | None: ...
    def save(self, ciclo: Ciclo) -> None: ...
    def delete(self, ciclo_id: UUID) -> None: ...
    def list_all(self) -> list[Ciclo]: ...


class CursoRepository(Protocol):
    def add(self, curso: Curso) -> None: ...
    def get(self, curso_id: UUID) -> Curso | None: ...
    def save(self, curso: Curso) -> None: ...
    def delete(self, curso_id: UUID) -> None: ...
    def list_all(self) -> list[Curso]: ...
    def list_by_ciclo(self, ciclo_id: UUID) -> list[Curso]: ...


class AsignaturaRepository(Protocol):
    def add(self, asignatura: Asignatura) -> None: ...
    def get(self, asignatura_id: UUID) -> Asignatura | None: ...
    def save(self, asignatura: Asignatura) -> None: ...
    def delete(self, asignatura_id: UUID) -> None: ...
    def list_all(self) -> list[Asignatura]: ...
