"""Puertos (interfaces de repositorio) del contexto TAXONOMÍA."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.contexts.taxonomy.domain.model import Asignatura, Ciclo, Curso


class CicloRepository(Protocol):
    def add(self, ciclo: Ciclo) -> None: ...
    def get(self, ciclo_id: UUID) -> Ciclo | None: ...
    def save(self, ciclo: Ciclo) -> None: ...
    def delete(self, ciclo_id: UUID) -> None: ...
    def list_all(self) -> list[Ciclo]: ...


class CursoRepository(Protocol):
    def add(self, curso: Curso) -> None: ...
    def get(self, curso_id: UUID) -> Curso | None: ...
    def save(self, curso: Curso) -> None: ...
    def delete(self, curso_id: UUID) -> None: ...
    def list_all(self) -> list[Curso]: ...
    def list_by_ciclo(self, ciclo_id: UUID) -> list[Curso]: ...


class AsignaturaRepository(Protocol):
    def add(self, asignatura: Asignatura) -> None: ...
    def get(self, asignatura_id: UUID) -> Asignatura | None: ...
    def save(self, asignatura: Asignatura) -> None: ...
    def delete(self, asignatura_id: UUID) -> None: ...
    def list_all(self) -> list[Asignatura]: ...


class ContenidoEnTaxonomia(Protocol):
    """Puerto para saber cuántos contenidos referencian una taxonomía (lo implementa CONTENIDO).

    Permite a los casos de uso de borrado proteger la integridad referencial sin que TAXONOMÍA
    dependa del contexto CONTENIDO: el adapter vive en infraestructura de ``content`` y se cablea
    en la capa de composición (el router). Cuenta todo el contenido NO purgado (incluida la
    papelera), porque un contenido en papelera puede restaurarse y su referencia sigue vigente.
    """

    def cuenta_por_curso(self, curso_id: UUID) -> int: ...
    def cuenta_por_asignatura(self, asignatura_id: UUID) -> int: ...
